version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/prisma
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - KONG_ADMIN_URL=${KONG_ADMIN_URL}
      - KONG_PUBLIC_DNS=${KONG_PUBLIC_DNS}
      - KONG_API_KEY=${KONG_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    command: sh -c "npx prisma generate && npm run dev"
    working_dir: /app  # Sets the working directory to /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
